export const browserCoreExamples = [
  "alienclaw browser status",
  "alienclaw browser start",
  "alienclaw browser stop",
  "alienclaw browser tabs",
  "alienclaw browser open https://example.com",
  "alienclaw browser focus abcd1234",
  "alienclaw browser close abcd1234",
  "alienclaw browser screenshot",
  "alienclaw browser screenshot --full-page",
  "alienclaw browser screenshot --ref 12",
  "alienclaw browser snapshot",
  "alienclaw browser snapshot --format aria --limit 200",
  "alienclaw browser snapshot --efficient",
  "alienclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "alienclaw browser navigate https://example.com",
  "alienclaw browser resize 1280 720",
  "alienclaw browser click 12 --double",
  'alienclaw browser type 23 "hello" --submit',
  "alienclaw browser press Enter",
  "alienclaw browser hover 44",
  "alienclaw browser drag 10 11",
  "alienclaw browser select 9 OptionA OptionB",
  "alienclaw browser upload /tmp/alienclaw/uploads/file.pdf",
  'alienclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "alienclaw browser dialog --accept",
  'alienclaw browser wait --text "Done"',
  "alienclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "alienclaw browser console --level error",
  "alienclaw browser pdf",
];
