/**
 * Shadow report generator — compares scalar loop vs reflective loop in shadow mode.
 *
 * Run after a shadow-mode session to see whether the reflective loop is outperforming
 * the scalar loop before flipping shadow → on.
 *
 * Usage: tsx src/alienclaw/evolution/reflective/shadow-report.ts > shadow-report.md
 */
import type { CandidateScore, ObjectiveVector } from "./types.js";

export interface ShadowRunRecord {
  scalarLoopWinnerLegacyScalar: number;
  reflectiveLoopWinnerHeldOut: ObjectiveVector | null;
  reflectiveLoopWinnerLegacyScalar: number;
  metricCallsScalar: number;
  metricCallsReflective: number;
  evalCountDelta: number;   // reflective - scalar
  costDeltaUsd: number;     // reflective - scalar cumulative cost
  acceptRate: number;       // fraction of mutations accepted
  frontierSize: number;
  overfitCount: number;
  frontier: CandidateScore[];
}

export function generateShadowReport(run: ShadowRunRecord, runAt: string): string {
  const reflHeldOut = run.reflectiveLoopWinnerHeldOut;
  const heldOutCorrectness = reflHeldOut ? reflHeldOut.correctness.toFixed(4) : "N/A";
  const scalarWinner = run.scalarLoopWinnerLegacyScalar.toFixed(4);
  const reflScalar = run.reflectiveLoopWinnerLegacyScalar.toFixed(4);
  const evalDeltaSign = run.evalCountDelta > 0 ? "+" : "";
  const costDeltaSign = run.costDeltaUsd > 0 ? "+" : "";

  // ASCII sparkline of correctness across frontier (sorted)
  const corr = run.frontier.map(c => c.aggregate.correctness).sort((a, b) => a - b);
  const sparkline = sparklineAscii(corr, 20);

  return `# Shadow Run Report — ${runAt}

## Verdict

| Metric | Scalar loop | Reflective loop | Delta |
|--------|-------------|-----------------|-------|
| Winner legacy scalar | ${scalarWinner} | ${reflScalar} | ${(Number(reflScalar) - Number(scalarWinner)).toFixed(4)} |
| Winner held-out correctness | (not measured) | ${heldOutCorrectness} | — |
| Eval count (metric calls) | ${run.metricCallsScalar} | ${run.metricCallsReflective} | ${evalDeltaSign}${run.evalCountDelta} |
| Cost delta (USD) | baseline | ${costDeltaSign}$${Math.abs(run.costDeltaUsd).toFixed(4)} | — |
| Child accept rate | — | ${(run.acceptRate * 100).toFixed(1)}% | — |
| Frontier size | — | ${run.frontierSize} | — |
| Overfit (demoted) | — | ${run.overfitCount} | — |

## Correctness curve (frontier, ascending)

\`${sparkline}\`

## Recommendation

${getRecommendation(run)}

---
*Generated by shadow-report.ts from a mock adapter run. Real campaign inputs required for production decision.*
`;
}

function sparklineAscii(values: number[], width: number): string {
  if (values.length === 0) return "no data";
  const CHARS = "▁▂▃▄▅▆▇█";
  const min = Math.min(...values);
  const max = Math.max(...values);
  const range = max - min || 1;
  // Resample to width
  const out: string[] = [];
  for (let i = 0; i < width; i++) {
    const idx = Math.floor((i / width) * values.length);
    const v = values[idx] ?? 0;
    const bucket = Math.min(7, Math.floor(((v - min) / range) * 8));
    out.push(CHARS[bucket] ?? "▁");
  }
  return out.join("");
}

function getRecommendation(run: ShadowRunRecord): string {
  const heldOut = run.reflectiveLoopWinnerHeldOut?.correctness ?? 0;
  const scalarScore = run.scalarLoopWinnerLegacyScalar;
  const delta = heldOut - scalarScore;

  if (run.overfitCount > 0) {
    return `⚠️  **WAIT** — ${run.overfitCount} finalist(s) were demoted for held-out regression. Tighten oracles or raise valsetFraction before enabling.`;
  }
  if (delta > 0.05) {
    return `✅  **Flip to ON** — reflective loop +${(delta * 100).toFixed(1)}pp on held-out vs scalar baseline. Cost is ${run.costDeltaUsd > 0 ? "higher" : "lower"} by $${Math.abs(run.costDeltaUsd).toFixed(4)}.`;
  }
  if (delta > 0) {
    return `🟡  **Continue shadowing** — marginal gain (+${(delta * 100).toFixed(1)}pp). Run more generations or add more verifiable oracles.`;
  }
  return `🔴  **Do not enable** — reflective loop underperforms scalar on held-out. Check oracle quality and accept rate.`;
}
