/**
 * test/integration/governance-live-fitness.test.ts
 *
 * E2 item 4 — governance live-fitness integration test.
 *
 * Verifies the full production chain:
 *   GovernanceLoop → RealMartianSummonAdapter (fromPopulation=true)
 *   → bridge subprocess → Population.add(fitness) → OnlineFitnessLog.record()
 *
 * Two complementary tests:
 *
 * Test 1 (Adapter + Population): Direct Subagent run with
 *   fromPopulation=true and explicit valid inputs. Verifies that the
 *   bridge creates/loads the Population and returns real fitness.
 *
 * Test 2 (GovernanceLoop chain): GovernanceLoop.spawnCampaign with a
 *   mock campaignCreatorBot that returns a pre-birthed real Subagent
 *   (real adapter, stored valid YAML). Verifies that on campaign
 *   success, onlineFitnessLog.record() is called with real fitness.
 *
 * Key technique: Subagent.birth(brief, yaml) stores the YAML;
 * runCampaign(brief, inputs) uses the stored YAML (priority 2 in the
 * 3-source lookup at subagent.ts:441). This lets us inject valid
 * compute inputs { input: "2 + 2" } even when GovernanceLoop generates
 * the brief with non-math inputs.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, existsSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import * as path from 'node:path';

import { GovernanceLoop } from '../../src/alienclaw/governance/common/governance-loop.js';
import type { GovernanceLoopDeps } from '../../src/alienclaw/governance/common/governance-loop.js';
import { RealMartianSummonAdapter } from '../../src/alienclaw/governance/common/real-summon-adapter.js';
import { Subagent } from '../../src/alienclaw/governance/common/subagent.js';
import type { SubagentBrief, SubagentOptions } from '../../src/alienclaw/governance/common/subagent.js';
import { OnlineFitnessLog } from '../../src/alienclaw/governance/common/online-fitness-log.js';
import { DomainResolver } from '../../src/alienclaw/governance/common/domain-resolver.js';
import type { Campaign, GoalsFile } from '../../src/alienclaw/types.js';

// ── Constants ──────────────────────────────────────────────────────────────

/**
 * Minimal single-step YAML that passes { input: "2 + 2" } directly to the
 * compute martian. Bypasses the default YAML generated by buildTransitionTableYaml
 * which sends { plan: "${campaign.plan}" } (not a valid math expression).
 */
const COMPUTE_YAML = `transition_table:
  initial_state: step1
  states:
    step1:
      martian_type: compute
      inputs:
        input: "2 + 2"
      transitions:
        - when: { all: [{ kind: martian_succeeded }] }
          goto: FINALIZE
        - when: { any: [{ kind: error_present }] }
          goto: "FAIL:compute_failed"
`;

// ── Helpers ────────────────────────────────────────────────────────────────

function makeMinimalBrief(campaignId: string): SubagentBrief {
  return {
    campaignId,
    role:               'compute Subagent',
    domain:             'compute',
    objective:          'evaluate 2 + 2',
    scope:              'compute',
    successCriteria:    'result is 4',
    allowedMartians:    ['compute'],
    deliverables:       'result',
    backgroundContext:  '',
    communicationStyle: 'terse',
    knowledgeBase:      '',
    constraints:        'None',
  };
}

function makeCampaign(override: Partial<Campaign> = {}): Campaign {
  return {
    id:        'e2-camp-1',
    name:      'e2 integration campaign',
    objective: 'evaluate 2 + 2',
    subagents: [{
      role:          'Compute Worker',
      domain:        'compute',
      knowledgeBase: '',
      martianTags:   ['compute'],
    }],
    dependsOn: [],
    status:    'pending',
    ...override,
  };
}

function makeMinimalDeps(opts: {
  campaignCreatorBot: any;
  resolver:           DomainResolver;
  fitnessLog:         OnlineFitnessLog;
}): GovernanceLoopDeps {
  const file: GoalsFile = { version: '1', activeGoalId: null, goals: [] };
  return {
    bossBot:           {} as any,
    advisorBot:        {} as any,
    creatorBot:        {
      flushNotable:  vi.fn(() => []),
      peekUrgent:    vi.fn(() => null),
      consumeUrgent: vi.fn(),
    } as any,
    agentRegistry:     {} as any,
    goalManager: {
      updateCampaign:    vi.fn(async () => {}),
      updateSubGoal:     vi.fn(async () => {}),
      load:              vi.fn(() => file),
      getReadyCampaigns: vi.fn(() => [] as Campaign[]),
      getReadySubGoals:  vi.fn(() => []),
    } as any,
    taskManager:       { register: vi.fn(), assign: vi.fn(), deregister: vi.fn() } as any,
    escalationHandler: {} as any,
    completionHandler: {} as any,
    userChannel: {
      status:   vi.fn(),
      verbose:  vi.fn(),
      required: vi.fn(),
      close:    vi.fn(),
    } as any,
    agentChannel:       {} as any,
    adapter:            {} as any,
    domainResolver:     opts.resolver,
    campaignCreatorBot: opts.campaignCreatorBot as any,
    onlineFitnessLog:   opts.fitnessLog,
  } as unknown as GovernanceLoopDeps;
}

// ── Suite ──────────────────────────────────────────────────────────────────

describe('E2 item 4 — governance live-fitness integration', () => {
  let tmpDir:   string;
  let popRoot:  string;
  let savedPop: string | undefined;

  beforeEach(() => {
    tmpDir  = mkdtempSync(path.join(tmpdir(), 'e2-live-fitness-'));
    popRoot = path.join(tmpDir, 'populations');
    savedPop = process.env['ALIENCLAW_POPULATIONS_ROOT'];
    process.env['ALIENCLAW_POPULATIONS_ROOT'] = popRoot;
  });

  afterEach(() => {
    if (savedPop !== undefined) {
      process.env['ALIENCLAW_POPULATIONS_ROOT'] = savedPop;
    } else {
      delete process.env['ALIENCLAW_POPULATIONS_ROOT'];
    }
    rmSync(tmpDir, { recursive: true, force: true });
  });

  // ── Test 1: Subagent + real adapter (fromPopulation=true) ─────────────────

  it(
    'Test 1: fromPopulation summon runs bridge, returns fitness > 0, creates Population',
    { timeout: 60_000 },
    async () => {
      const adapter   = new RealMartianSummonAdapter();
      const subagent  = new Subagent(adapter, {
        campaignId:       'e2-t1',
        martianType:      'compute',
        inputs:           { input: '2 + 2' },
        timeoutMs:        30_000,
        fromPopulation:   true,
        subagentsBaseDir: tmpDir,
      } as SubagentOptions);

      const brief = makeMinimalBrief('e2-t1');
      subagent.birth(brief, COMPUTE_YAML);

      const result = await subagent.runCampaign(brief, { input: '2 + 2' });

      // Bridge ran and compute martian succeeded (2 + 2 = 4 is valid math)
      expect(result.termination_reason).toBe('state_machine_finalized');
      expect(result.fitness).toBeGreaterThan(0);
      expect(result.summon_count).toBeGreaterThan(0);

      // Bridge created the Population directory (load_or_create was called)
      expect(existsSync(popRoot)).toBe(true);

      subagent.erase();
    },
  );

  // ── Test 2: GovernanceLoop → real adapter → OnlineFitnessLog ─────────────

  it(
    'Test 2: GovernanceLoop.spawnCampaign with real bridge records fitness to OnlineFitnessLog',
    { timeout: 60_000 },
    async () => {
      const fitnessLog = new OnlineFitnessLog(path.join(tmpDir, 'fitness.jsonl'));
      const resolver   = new DomainResolver(['compute']);

      // Build the Subagent pre-birthed with valid YAML so the compute martian
      // receives { input: "2 + 2" } instead of the default { plan: "..." }.
      const adapter     = new RealMartianSummonAdapter();
      const preSubagent = new Subagent(adapter, {
        campaignId:       'e2-camp-1',
        martianType:      'compute',
        inputs:           { input: '2 + 2' },
        timeoutMs:        30_000,
        fromPopulation:   true,
        subagentsBaseDir: tmpDir,
      } as SubagentOptions);
      const brief = makeMinimalBrief('e2-camp-1');
      preSubagent.birth(brief, COMPUTE_YAML);  // stores YAML; birth() is idempotent

      // campaignCreatorBot returns the pre-birthed Subagent
      const campaignCreatorBot = {
        buildSubagent: vi.fn(() => preSubagent),
      };

      const deps = makeMinimalDeps({ campaignCreatorBot, resolver, fitnessLog });
      const loop = new GovernanceLoop(deps);

      // Trigger campaign — spawnCampaign calls birth() (no-op) then runCampaign
      await (loop as any).spawnCampaign('goal-e2', makeCampaign());
      const job: Promise<void> | undefined = (loop as any).activeJobs.get('e2-camp-1');
      if (job) await job;

      // OnlineFitnessLog must have an entry from GovernanceLoop line 418:
      //   this.onlineFitnessLog?.record(martianType, campaignResult.fitness)
      const entries = fitnessLog.read();
      expect(entries.length).toBeGreaterThanOrEqual(1);
      expect(entries[0]!['martian_type']).toBe('compute');
      expect(entries[0]!['fitness']).toBeGreaterThan(0);

      // Population was created (bridge called load_or_create)
      expect(existsSync(popRoot)).toBe(true);
    },
  );
});
